- name: K8 master
  block:
    # OBS! Error when this task have already been done
    - name: Initializing k8s cluster
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=All #--ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

    - name: Check if $HOME/.kube exists
      stat:
        path: $HOME/.kube
      become: yes
      become_user: ubuntu
      register: file_data

    - name: Setting up kubectl on Master Node if not been done before
      shell:
        cmd: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
      become: yes
      become_user: ubuntu
      when: not file_data.stat.exists

    - name: Deploying calico network
      become: yes
      become_user: ubuntu
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Add user Ubuntu to Docker
      command: usermod -aG docker ubuntu
