---
# Source: ChattApp/templates/pvc/pg-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: postgresql-db-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-sc
