# This file defines the pipeline that runs when
# pushing to gitlab! // STEFFE
variables:
  TESTVAR: hejhej

stages:
  - hello-world
  - build

test:
  image: node:latest
  stage: hello-world
  script:
    - echo "hello $TESTVAR"
  only: 
    - pipeline-test

# (jag testar bara)
build_npm1:
  image: node:latest
  stage: build
  script:
   - npm install ./server
  only: 
    - pipeline-test
  except:
    changes:
      - infrastructure/*
  artifacts:
    name: npm_server
    when: on_success
    paths:
      - node_modules/
