include:
  - local: '/build.gitlab-ci.yml'
  #- local: '/test.gitlab-ci.yml'
  #- local: '/acceptance.gitlab-ci.yml'
  - local: '/deploy.gitlab-ci.yml'
  - local: '/compile.gitlab-ci.yml'
image: docker:18.09.7-dind
services:
  - docker:18.09.7-dind

variables:
  IMG_REGISTRY: $CI_REGISTRY/2dv612/student/team-1---ht21/project

stages:
  - compile
  - test
  - build
  - acceptance
  - deploy

