include:
  - local: '.gitlab-ci/vars.gitlab-ci.yml'
  - local: '.gitlab-ci/rules.gitlab-ci.yml'
  - local: '.gitlab-ci/install_dependencies.gitlab-ci.yml'
  - local: '.gitlab-ci/test.gitlab-ci.yml'
  - local: '.gitlab-ci/build.gitlab-ci.yml'
  #- local: '.gitlab-ci/acceptance.gitlab-ci.yml'
  - local: '.gitlab-ci/deploy.gitlab-ci.yml'


stages:
  # - install-dependencies
  # - test
  # - build
  # - acceptance
  - deploy

npm-install-client:
  extends: .npm-install
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH


npm-install-server:
  extends: .npm-install
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

test-eslint-client:
  extends: .eslint
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

test-eslint-server:
  extends: .eslint
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

build-npm-client:
  extends: .build-npm
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

build-npm-server:
  extends: .build-npm
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

build-image-client:
  needs: ["build-npm-client"]
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

build-image-server:
  needs: ["build-npm-server"]
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

build-image-postgres:
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_POSTGRES_PATH

create-manifests:
  extends: .create-manifests

deploy-all:
  needs: ["create-manifests"]
  extends: .deploy


