include:
  - local: 'vars.gitlab-ci.yml'
  - local: 'compile.gitlab-ci.yml'
  #- local: 'test.gitlab-ci.yml'
  - local: 'build.gitlab-ci.yml'
  #- local: 'acceptance.gitlab-ci.yml'
  - local: 'deploy.gitlab-ci.yml'


stages:
  - compile
  - test
  - build
  - acceptance
  - deploy

compile-client:
  extends: .compile-npm
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

compile-server:
  extends: .compile-npm
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

# build:static-client:
#   extends: .build:static
#   variables:
#     CI_APP_PATH: $CI_CLIENT_PATH

build:image-client:
  extends: .build:image
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

build:image-server:
  extends: .build:image
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

build:image-postgres:
  extends: .build:image
  variables:
    CI_APP_PATH: $CI_POSTGRES_PATH

deploy-all:
  extends: .deploy

# build-image-server:
#   extends: .build-image
#   variables:

