include:
  - local: '.gitlab-ci/vars.gitlab-ci.yml'
  - local: '.gitlab-ci/compile.gitlab-ci.yml'
  #- local: '.gitlab-ci/test.gitlab-ci.yml'
  - local: '.gitlab-ci/build.gitlab-ci.yml'
  #- local: '.gitlab-ci/acceptance.gitlab-ci.yml'
  - local: '.gitlab-ci/deploy.gitlab-ci.yml'

stages:
  - compile
  - test
  - build
  - acceptance
  - deploy

cache:
  paths:
    - $CLIENT_PATH/build
    - $SERVER_PATH/build


compile-client:
  extends: .compile-npm
  variables:
    NPM_APP_PATH: $CLIENT_PATH

compile-server:
  extends: .compile-npm
  variables:
    NPM_APP_PATH: $SERVER_PATH

build-image-client:
  extends: .build-image
  variables:
    PATH: $CLIENT_PATH

build-image-server:
  extends: .build-image
  variables:
    PATH: $SERVER_PATH    