include:
  - local: '/.gitlab-ci-build.yml'
  #- local: '/.gitlab-ci-test.yml'
  #- local: '/.gitlab-ci-acctest.yml'
  - local: '/.gitlab-ci-deploy.yml'

variables:
  IMG_REGISTRY: $CI_REGISTRY/2dv612/student/team-1---ht21/project

stages:
  - build
  - test
  - acceptance
  - deploy


