include:
  - local: ".gitlab-ci/vars.gitlab-ci.yml"
  - local: ".gitlab-ci/rules.gitlab-ci.yml"
  - local: ".gitlab-ci/install_dependencies.gitlab-ci.yml"
  - local: ".gitlab-ci/test.gitlab-ci.yml"
  - local: ".gitlab-ci/build.gitlab-ci.yml"
  - local: ".gitlab-ci/staging.gitlab-ci.yml"
  - local: ".gitlab-ci/deploy.gitlab-ci.yml"

# En ändring till

stages:
  - install-dependencies
  - test
  - build
  - staging
  - deploy

# Install dependencies
npm-install-client:
  extends: .npm-install
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

npm-install-server:
  extends: .npm-install
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

# Unit tests
test-eslint-client:
  needs: ["npm-install-client"]
  extends: .eslint
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

test-eslint-server:
  needs: ["npm-install-server"]
  extends: .eslint
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

test-unit-server:
  needs: ["npm-install-server"]
  extends: .unit-test
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

test-unit-client:
  needs: ["npm-install-client"]
  script:
    - echo "todo"

## Build
build-npm-client:
  extends: .build-npm
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

build-npm-server:
  extends: .build-npm
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

# Images
build-image-client:
  needs: ["build-npm-client"]
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_CLIENT_PATH

build-image-server:
  needs: ["build-npm-server"]
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

build-image-postgres:
  extends: .build-image
  variables:
    CI_APP_PATH: $CI_POSTGRES_PATH

build-manifests:
  extends: .create-manifests

# == Deploy to staging and run acceptance/smoke tests ==
deploy-staging-env:
  extends: .deploy-test-env

run-staging-tests:
  needs: ["deploy-staging-env"]
  extends: .acc-test
  variables:
    CI_APP_PATH: $CI_SERVER_PATH

cleanup-staging-env:
  needs: ["run-staging-tests"]
  extends: .cleanup

# Deploy to production

deploy-production:
  extends: .deploy  