# This file defines the pipeline that runs when
# pushing to gitlab! // STEFFE
variables:
  TESTVAR: hejhej

stages:
  - hello-world
  - build

test:
  image: node:latest
  stage: hello-world
  script:
    - mkdir testing && echo "hello $TESTVAR" >> testing/hello.txt
  only: 
    - pipeline-test

# Test building node_modules in /server and store it in artifact repository
build_npm1:
  image: node:latest
  stage: build
  script:
   - npm install ./server
  only:             # Pipeline will only trigger on commits 
    - pipeline-test # to this branch
  except: # ignore anton's work
    changes:
      - infrastructure/*
  artifacts:
    name: hello
    when: on_success
    paths:
      - node_modules/
  environment:
    name: not_production

# Artifacts /client
build_npm2:
  image: node:latest
  stage: build
  script:
   - npm install ./client
  only: 
    - pipeline-test
  except: # ignore anton's work
    changes:
      - infrastructure/*
  artifacts:
    name: npm_client
    when: on_success
    paths:
      - node_modules/
  environment:
    name: not_production