include:
  - local: '.gitlab-ci/vars.gitlab-ci.yml'
  - local: '.gitlab-ci/compile.gitlab-ci.yml'
  #- local: '.gitlab-ci/test.gitlab-ci.yml'
  - local: '.gitlab-ci/build.gitlab-ci.yml'
  #- local: '.gitlab-ci/acceptance.gitlab-ci.yml'
  - local: '.gitlab-ci/deploy.gitlab-ci.yml'

stages:
  - $CI_COMPILE_STAGE
  - $CI_TEST_STAGE
  - $CI_BUILD_STAGE
  - $CI_ACCEPTANCE_STAGE
  - $CI_DEPLOY_STAGE


# cache:
#   paths:
#     - $CI_CLIENT_PATH/build
#     - $CI_SERVER_PATH/build


# compile-client:
#   extends: .compile-npm
#   variables:
#     CI_NPM_APP_PATH: $CLIENT_PATH

# compile-server:
#   extends: .compile-npm
#   variables:
#     CI_NPM_APP_PATH: $SERVER_PATH

build-image-client:
  extends: .build-image
  variables:
    CI_BUILD_PATH: $CLIENT_PATH

# build-image-server:
#   extends: .build-image
#   variables:

