# This file defines the pipeline that runs when
# pushing to gitlab! // STEFFE
variables:
  TESTVAR: hejhej

stages:
  - hello-world
  - build

test:
  image: node:latest
  stage: hello-world
  script:
    - echo "hello $TESTVAR"
  only: 
    - pipeline-test

# Test building node_modules in /server and store it in artifact repository
build_npm1:
  image: node:latest
  stage: build
  script:
   - npm install ./server
  only: 
    - pipeline-test
  except: # ignore anton's work
    changes:
      - infrastructure/*
  artifacts:
    name: npm_server
    when: on_success
    paths:
      - node_modules/

# Artifacts /client
build_npm2:
  image: node:latest
  stage: build
  script:
   - npm install ./client
  only: 
    - pipeline-test
  except: # ignore anton's work
    changes:
      - infrastructure/*
  artifacts:
    name: npm_client
    when: on_success
    paths:
      - node_modules/