apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: pg-img
    context: postgres

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      # Node server
      # Postgres
      - image: pg-img
        context: postgres
        docker:
          buildArgs:
            ENV: dev
      # Client