apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: local
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
        - k8s-dev/postgres.yaml
        - k8s-dev/pgadmin.yaml
        - k8s-dev/vars.yaml
    build:
      artifacts:
      # Postgres
      - image: pg-img
        context: postgres
        docker:
          buildArgs:
            ENV: dev

            