apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: node-img
    context: server

  - image: pg-img
    context: postgres

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: node-img
        context: server
        docker:
          buildArgs:
            ENV: dev
        sync:
          manual:
          - src: 'src/*'
            dest: .
      - image: pg-img
        context: postgres
        docker:
          buildArgs:
            ENV: dev