# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{.Values.db_env_name}}
  name: {{.Values.postgres_name}}
spec:
  serviceName: {{.Values.postgres_svc}}
  selector:
    matchLabels:
      app: {{.Values.postgres_name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.postgres_name}}
    spec:
      containers:
        - name: {{.Values.postgres_name}}
          image: {{.Values.postgres_img}}
          imagePullPolicy: Always
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_PASSWORD
      imagePullSecrets:
        - name: regcred
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: {{.Values.storageclass_name}}
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.db_env_name}}
  name: {{.Values.postgres_svc}}
spec:
  selector:
    app: {{.Values.postgres_name}}
  ports:
    - port: {{.Values.postgres_port}}
      targetPort: {{.Values.postgres_port}}
