- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ kube_dir }}'
    state: directory
    mode: '0777'

- name: Copying templates
  become: yes
  become_user: ubuntu
  template:
    src: '{{ item.local }}'
    dest: '{{ item.remote }}'
  loop:
    - { local: 'provisioner-dep.yml.j2',remote: '{{ kube_dir }}/provisioner-dep.yml',}
    - { local: 'proxy-cm.yml.j2', remote: '{{ kube_dir }}/proxy-cm.yml' }
    - { local: 'global-vars.yml.j2', remote: '{{ kube_dir }}/global-vars.yml' }

- name: Deploy configs
  become: yes
  become_user: ubuntu
  command: kubectl apply -f ~/{{ kube_dir }}/
