
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ kube_dir }}'
    state: directory
    mode: '0777'

- name: Copying templates
  become: yes
  become_user: ubuntu
  template:
    src: '{{ item.local }}'
    dest: '{{ item.remote }}'
  loop:
    - { local: 'provisioner-dep.yml.j2',remote: '{{ kube_dir }}/provisioner-dep.yml',}
    - { local: 'proxy-cm.yml.j2', remote: '{{ kube_dir }}/proxy-cm.yml' }
    - { local: 'global-vars.yml.j2', remote: '{{ kube_dir }}/global-vars.yml' }
    - { local: 'git-runner-conf.yml.j2', remote: '{{ kube_dir }}/git-runner-conf.yml' }

- name: Deploy configs
  become: yes
  become_user: ubuntu
  shell: | 
    helm template --values k8s/git-runner-conf.yml --output-dir ~/{{ kube_dir }}/ gitlab/gitlab-runner
    kubectl apply -f ~/{{ kube_dir }}/ --recursive

#    kubectl create secret docker-registry regcred --docker-server="{{git_reg}}" --docker-username="{{git_token}}" --docker-password="{{git_username}}"
#   helm install --namespace default gitlab-runner -f ~/{{ kube_dir }}/git-runner-conf.yml gitlab/gitlab-runner