.acc-test:
  image: node:16-alpine
  stage: acceptance
  script:
    - cd $CI_APP_PATH
    - ls -la
    - npm run test:acc
  cache:
    key: "$CI_APP_PATH-dev-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
  tags:
    - $CI_RUNNER_TAG
