.compile-npm:
  # only:
  #   changes:
  #     - $CI_APP_PATH/package.json
  stage: compile
  image: node:16-alpine
  variables:
    CI: "false" # Must be added to allow for warnings during build using craco
  script:
    - ls -la
    - echo $CI_APP_PATH
    - cd $CI_APP_PATH
    - npm ci && npm cache clean --force
    #- npm run build
    - ls -la
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
  tags:
    - $CI_RUNNER_TAG
