.compile-npm:
  stage: compile
  image: node:16-alpine
  variables:
    CI: "false" # Must be added to allow for warnings during build using craco
  script:
    - echo $CI_APP_PATH
    - cd $CI_APP_PATH
    - ls -la
    - npm ci --legacy-peer-deps && npm cache clean --force
    - npm run build
    - ls -la
  cache:
    key: "$CI_APP_PATH-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
      - $CI_APP_PATH/build
  tags:
    - $CI_RUNNER_TAG

