.deploy:
  stage: $CI_DEPLOY_STAGE
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] # default entry point is kubectl but we want to create the kubeconf first.
  variables:
    test: $IMG_REGISTRY:$CI_COMMIT_BRANCH
  before_script:
    - touch /.kube/config
    - echo "$K8_CONFIG" > /.kube/config
    - cat /.kube/config
  script:
    - kubectl delete -f k8s/ --ignore-not-found
    - kubectl delete secret regcred  --ignore-not-found
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username="$GIT_USERNAME" --docker-password="$GIT_TOKEN"
    - kubectl apply -f k8s/
  tags:
    - $CI_RUNNER_TAG

# Only runs on main branch.
# deploy-main:
#   rules:
#     if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   script:
#     echo "example job $CI_COMMIT_BRANCH"
