.create-manifests:
  stage: deploy
  rules:
    - !reference [.rules-deploy, rules]
  image:
    name: alpine/helm
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        env="production"
        echo "Running on default branch '$CI_DEFAULT_BRANCH'"
      else
        tag="$CI_COMMIT_SHORT_SHA"
        env="development"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - cd helm
    - helm template . --output-dir manifests --set lb_ip="194.47.177.79" --set env_name=${env} --set server_img=${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${CI_SERVER_PATH}:${tag} --set client_img=${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${CI_CLIENT_PATH}:${tag} --set postgres_img=${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${CI_POSTGRES_PATH}:${tag}
  artifacts:
    paths:
      - helm/manifests
  tags:
    - $CI_RUNNER_TAG

.deploy:
  stage: deploy
  rules:
    - !reference [.rules-deploy, rules]
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] # default entry point is kubectl but we want to create the kubeconf first.
  variables:
    test: $IMG_REGISTRY:$CI_COMMIT_BRANCH
  before_script:
    - touch /.kube/config
    - echo "$K8_CONFIG" > /.kube/config
    - cat /.kube/config
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        env="production"
        echo "Running on default branch '$CI_DEFAULT_BRANCH'"
      else
        env="development"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - cd helm/manifests/ChattApp/templates
    - ls -la
    - kubectl create secret docker-registry regcred --namespace="$env" --docker-server="$CI_REGISTRY" --docker-username="$GIT_USERNAME" --docker-password="$GIT_TOKEN" --dry-run=client -o yaml > regcred.yaml
    - kubectl delete -f ./ --ignore-not-found
    - kubectl apply -f ./
  tags:
    - $CI_RUNNER_TAG


