.deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] # default entry point is kubectl but we want to create the kubeconf first.
  variables:
    test: $IMG_REGISTRY:$CI_COMMIT_BRANCH
  before_script:
    - touch /.kube/config
    - echo "$K8_CONFIG" > /.kube/config
    - cat /.kube/config
  script:
    - echo $CI_REGISTRY
    - echo $GIT_USERNAME
    - echo $GIT_TOKEN
    - kubectl delete -f k8s/ --ignore-not-found
    - kubectl delete secret regcred  --ignore-not-found
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username="$GIT_USERNAME" --docker-password="$GIT_TOKEN"
    - sed -i --expression "s@client-img@${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/client:client@" k8s/client.yaml
    - sed -i --expression "s@server-img@${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/server:server@" k8s/koa.yaml
    - sed -i --expression "s@postgres-img@${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/postgres:postgres@" k8s/postgres.yaml
    - kubectl apply -f k8s/
  tags:
    - $CI_RUNNER_TAG

# Only runs on main branch.
# deploy-main:
#   rules:
#     if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   script:
#     echo "example job $CI_COMMIT_BRANCH"
