.npm-install:
  # rules:
  #   - !reference [.rules-compile-npm, rules]
  stage: install-dependencies
  image: node:16-alpine
  variables:
    CI: "false" # Must be added to allow for warnings during build using craco commentary
  script:
    - cd $CI_APP_PATH
    - echo $CI_APP_PATH
    - ls -la
    - npm install --only=dev
    - ls -la
  cache:
    key: "$CI_APP_PATH-dev-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
  tags:
    - $CI_RUNNER_TAG
