.rules-deploy:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.rules-build:
  changes:
    - $CI_APP_PATH/*

.rules-compile-npm:
  rules:
    - changes: # Run the job if the package.json file has been modified.
        - $CI_APP_PATH/package.json
