.rules-deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_COMMIT_BRANCH == 'dev'
    
.rules-compile-npm:
  rules:
    - changes: # Run the job if the package.json file has been modified.
        - $CI_APP_PATH/package.json
      when: always
    - exists: # Do NOT run the job if node_modules exists & package.json is not modified.
      - server/node_modules
      when: never
    - when: always # Always run the job if the node_modules folder is missing
