.rules-deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_COMMIT_BRANCH == 'dev'
    
.rules-compile-npm:
  rules:
    - changes:
        - $CI_APP_PATH/package.json
      when: always
    - exists:
      - node_modules
      when: never
    - when: always
