.rules-deploy:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.rules-build:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - $CI_APP_PATH/**/*

.rules-compile-npm:
  rules:
    - changes: # Run the job if the package.json file has been modified.
        - $CI_APP_PATH/package.json
        
.rules-test:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      allow_failure: true
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      allow_failure: false
      