
variables:
  TF_ROOT: ${CI_PROJECT_DIR}/infrastructure
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/terraform-state


cache:
  key: terraform-state
  paths:
    - ${TF_ROOT}/.terraform


apply:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform
  before_script:
    - cd $TF_ROOT
    - echo "$TF_VARS" > terraform.tfvars
    - echo "$PRIVATE_KEY" > encoded
    - base64 -d encoded > key.pem
  script:
    - ls -la
    - echo ${CI_PROJECT_ID}
    - gitlab-terraform plan

