# Eslint test
.eslint:
  image: node:16-alpine
  stage: test
  script:
    - echo test $CI_APP_PATH eslint here
    - cd $CI_APP_PATH
    - ls -la
    - npm run lint
  cache:
    key: "$CI_APP_PATH-test-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
  tags:
    - $CI_RUNNER_TAG

# Unit test
.unit-test:
  image: node:16-alpine
  stage: test
  script:
    - echo unit-test $CI_APP_PATH here
    - cd $CI_APP_PATH
    - ls -la
    - npm run ci
    - ls -la
  cache:
    key: "$CI_APP_PATH-test-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_APP_PATH/node_modules
  tags:
    - $CI_RUNNER_TAG
