.eslint:
  image: node:16-alpine
  stage: test
  script:
    - echo test $CI_APP_PATH eslint here
    - cd $CI_APP_PATH
    - npm run lint
  tags:
    - $CI_RUNNER_TAG

.unit-test:
  image: node:16-alpine
  stage: test
  script:
    - echo unit-test $CI_APP_PATH here
    - cd $CI_APP_PATH
    - npm test
  tags:
    - $CI_RUNNER_TAG
