.eslint:
  stage: test
  script:
    - echo test $CI_APP_PATH eslint here
  tags:
    - $CI_RUNNER_TAG

.unit-test:
  stage: test
  script:
    - echo unit-test $CI_APP_PATH here
  tags:
    - $CI_RUNNER_TAG   
