apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.env_name}}
  name: {{.Values.server_svc}}
spec:
  ports:
  - port: {{.Values.server_port}}
  selector:
    app: {{.Values.server_name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.env_name}}
  name: {{.Values.server_name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.server_name}}
  template:
    metadata:
      labels:
        app: {{.Values.server_name}}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: {{.Values.server_name}}
        image: {{.Values.server_img}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: all-vars
      imagePullSecrets:
        - name: regcred
