---
- name: Create infrastructures
  block:
    - name: Running terraform apply
      shell:
        cmd: terraform apply -auto-approve
      no_log: True

  rescue:
    - debug:
        msg: 'Server(s) failed during creation, trying to build again'
    - include_tasks: rescue.yml
