---
# Tasks for role infrastructure
- name: Descrypt clouds.yaml
  shell:
    cmd: ansible-vault decrypt clouds.yaml --vault-password-file=.vault/password.txt

- name: Init terraform
  shell:
    cmd: terraform init

- name: Initiate infrastructures
  include_tasks: create.yml

- name: Setup tasks for the automation process
  include_tasks: setup.yml

- name: Encrypt clouds.yaml
  shell:
    cmd: ansible-vault encrypt clouds.yaml
