apiVersion: v1
kind: Service
metadata:
  name: react-client-svc
spec:
  ports:
  - port: 3000
  selector:
    app: react-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      volumes:
        - name: react-vol
          persistentVolumeClaim:
            claimName: react-pvc
      containers:
      - name: react-client
        image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/client:pipeline-test2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: "/build"
            name: react-vol
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-proxy
  labels:
    app: react-proxy
spec:
  selector:
    matchLabels:
      app: react-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: react-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx/conf.d/
            - name: proxy-vol
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-proxy-config
            items:
              - key: nginx.conf
                path: default.conf
        - name: proxy-vol
          persistentVolumeClaim:
            claimName: react-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: react-proxy-svc
spec:
  selector:
    app: react-proxy
  ports:
  - protocol: TCP
    port: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    server {
        listen      *;

        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-pvc
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi