apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-proxy
  labels:
    app: react-proxy
spec:
  selector:
    matchLabels:
      app: react-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: react-proxy
    spec:
      containers:
        - name: nginx
          image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/client:pipeline-test2
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: react-proxy-svc
spec:
  type: NodePort
  selector:
    app: react-proxy
  ports:
  - protocol: TCP
    port: 3001
    nodePort: 32163

