apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: nginx
          image: client-img
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: all-vars
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: react-frontend-svc
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 3001
    nodePort: 32165

