apiVersion: v1
kind: Service
metadata:
  name: react-client-svc
spec:
  ports:
  - port: 3000
  selector:
    app: react-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/client:pipeline-test2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # envFrom:
        # - configMapRef:
        #     name: all-vars
      imagePullSecrets:
        - name: regcred
