apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: nginx
          image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/pipeline-test2/client
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: react-frontend-svc
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 3001
    nodePort: 32165

