apiVersion: v1
kind: Service
metadata:
  name: koa-backend-svc
spec:
  ports:
  - port: 5000
  selector:
    app: koa-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koa-backend
spec:
  selector:
    matchLabels:
      app: koa-backend
  template:
    metadata:
      labels:
        app: koa-backend
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: koa-backend
        image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/pipeline-test2/server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: all-vars
      imagePullSecrets:
        - name: regcred
