apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
  - port: 5000
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: node
        image: gitlab.lnu.se:5050/2dv612/student/team-1---ht21/project/koa:pipeline-test2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: all-vars
      imagePullSecrets:
        - name: regcred
