apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
  - port: 5000
  type: LoadBalancer
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: node
        image: node-img
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: all-vars