apiVersion: v1
kind: Service
metadata:
  name: node-client-svc
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: node-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-client
spec:
  selector:
    matchLabels:
      app: node-client
  template:
    metadata:
      labels:
        app: node-client
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: node-client
        image: node-client-img
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # envFrom:
        # - configMapRef:
        #     name: all-vars