apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: nginxconfig
            items:
              - key: nginx.conf
                path: default.conf
---
kind: Service
apiVersion: v1
metadata:
  name: proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32162
---