---
# Source: ChattApp/templates/proxy-dep.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: development
  name: nginxconfig
data:
  nginx.conf: |
    upstream svc {
        server client-frontend-svc.development.svc.cluster.local:3001 fail_timeout=0;
    }

    upstream koa {
        server koa-backend-svc.development.svc.cluster.local:5000 fail_timeout=0;
    }

    upstream pgadmin {
        server pgadmin-svc.development.svc.cluster.local:4000 fail_timeout=0;
    }
    
    server {
        listen      80;
        server_name http://localhost/;

        location / {
            proxy_pass http://svc;
        }

        location /pgadmin/ {
            proxy_set_header X-Script-Name /pgadmin4;
            proxy_set_header Host $host;
            proxy_pass http://pgadmin/;
            proxy_redirect off;
        }

        
        location /api {
            proxy_pass http://koa;
        }

        location /socket.io {
                proxy_pass http://koa;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                
                proxy_http_version 1.1;
                
                proxy_set_header X-Forwarded-Port: $server_port;
                proxy_set_header X-Forwarded-Host: $host;
                proxy_set_header X-Forwarded-Proto: $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-NginX-Proxy true;
                proxy_redirect off;
        }
    }
---
# Source: ChattApp/templates/proxy-dep.yaml
kind: Service
apiVersion: v1
metadata:
  namespace: development
  name: proxy-svc
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32162
---
# Source: ChattApp/templates/proxy-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: nginxconfig
            items:
              - key: nginx.conf
                path: default.conf
