---
# tasks file for nfs-server
- name: Creating mountable shared folders
  file:
    path: '{{ item }}'
    state: directory
  loop: '{{ shared_dir }}'

- name: Change mode {{ shared_dir[0] }}
  file:
    path: '{{ shared_dir[0] }}'
    mode: 0777
    owner: '1001'
    group: '1001'
    recurse: yes
    state: directory

- name: Install nfs package
  apt:
    name: nfs-kernel-server
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Starting nfs server
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: Configure nfs server
  template:
    src: export_file.j2
    dest: /etc/exports
  notify:
    - Restart nfs

