---
# Source: ChattApp/templates/postgres.yaml
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: pg-svc
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# Source: ChattApp/templates/postgres.yaml
# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: development
  name: postgres
spec:
  serviceName: pg-svc
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres-img
          imagePullPolicy: Always
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: all-vars
                  key: POSTGRES_PASSWORD
      imagePullSecrets:
        - name: regcred
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: nfs-sc
