- name: Getting servers stuck in build
  shell: chdir=../ openstack --os-cloud=openstack server list -f json | jq '.[] | select(.Status == "BUILD") | .Name'
  register: result
  ignore_errors: yes

- debug: msg="Server(s) failed during creation:{{ result.stdout_lines }}"

- name: Removing failed server(s)..
  shell: chdir=../ openstack --os-cloud=openstack server delete "{{item}}" 
  loop: "{{result.stdout_lines}}"

- name: Waiting for removed server(s) to die
  pause:
    seconds: 15

- name: Retrying..
  include_tasks: create.yml
  when: scale_cluster is not defined

- name: Retrying..
  include_tasks: scale-up.yml
  when: (scale_cluster is defined) and (scale_type | int == 1)

- name: Retrying..
  include_tasks: scale-down.yml
  when: (scale_cluster is defined) and (scale_type | int == 0)
